-- ─── service_category ────────────────────────────────────────────────────────
CREATE TABLE service_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order  INT DEFAULT 0 NOT NULL
);

-- ─── service ─────────────────────────────────────────────────────────────────
-- Named "service" in DB; mapped to ServiceItem in Java to avoid Spring clash.
CREATE TABLE service (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      BIGINT NOT NULL REFERENCES service_category(id),
    name             VARCHAR(150) NOT NULL,
    description      VARCHAR(1000),
    duration_minutes INT NOT NULL,
    price_from       INT,
    price_to         INT,
    active           BOOLEAN DEFAULT TRUE NOT NULL
);

-- ─── car_brand ───────────────────────────────────────────────────────────────
CREATE TABLE car_brand (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- ─── car_model ───────────────────────────────────────────────────────────────
CREATE TABLE car_model (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES car_brand(id),
    name     VARCHAR(80) NOT NULL
);

-- ─── client ──────────────────────────────────────────────────────────────────
CREATE TABLE client (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id  BIGINT NOT NULL UNIQUE,
    telegram_username VARCHAR(100),
    first_name        VARCHAR(100),
    phone             VARCHAR(20),
    created_at        TIMESTAMP NOT NULL
);

-- ─── car ─────────────────────────────────────────────────────────────────────
CREATE TABLE car (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES client(id),
    brand_id    BIGINT NOT NULL REFERENCES car_brand(id),
    model_id    BIGINT NOT NULL REFERENCES car_model(id),
    manufacture_year INT,
    engine_info VARCHAR(100),
    created_at  TIMESTAMP NOT NULL
);

-- ─── booking ─────────────────────────────────────────────────────────────────
-- status: PENDING → CONFIRMED → COMPLETED | PENDING → REJECTED | CONFIRMED → CANCELLED
-- service_id is NULL when client described problem in free text (admin assigns later)
CREATE TABLE booking (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id           BIGINT NOT NULL REFERENCES client(id),
    car_id              BIGINT NOT NULL REFERENCES car(id),
    service_id          BIGINT REFERENCES service(id),
    problem_description VARCHAR(1000),
    scheduled_at        TIMESTAMP NOT NULL,
    end_at              TIMESTAMP NOT NULL,
    status              VARCHAR(20) NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    confirmed_at        TIMESTAMP,
    notes               VARCHAR(1000)
);

-- ─── working_hours ───────────────────────────────────────────────────────────
-- day_of_week: 1=Mon … 7=Sun (ISO 8601)
CREATE TABLE working_hours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INT NOT NULL UNIQUE,
    open_time   TIME NOT NULL,
    close_time  TIME NOT NULL,
    is_working  BOOLEAN DEFAULT TRUE NOT NULL
);

-- ─── bot_state ───────────────────────────────────────────────────────────────
-- Persists multi-step conversation state so bot restarts don't lose users.
-- state_data is JSON stored as TEXT (switch to JSONB on PostgreSQL prod).
CREATE TABLE bot_state (
    telegram_user_id BIGINT PRIMARY KEY,
    current_state    VARCHAR(50),
    state_data       TEXT,
    updated_at       TIMESTAMP
);
